Refactor failed heartbeats log
uber-go/cadence-client pull request #1273
Opened 2023-09-20 12:09 UTC by jakobht

**What changed?**
Refactored the type check to use modern Go 

**What changed?**
In modern go typecasting errors is sometimes not correct as they might be wrapped, the errors.As method is aware of this and checks all wrapped errors 

**How did you test it?**
Tested locally

**Potential risks**
Worst case we log too much/too little

2023-09-20 12:39 UTC, 3vilhamster commented on internal/internal_task_handlers.go
> +			if errors.As(err, &canceledErr) {
You need to reverse the check.

2023-09-20 12:40 UTC, jakobht commented on internal/internal_task_handlers.go
> +			if errors.As(err, &canceledErr) {
Yep, thanks!

2023-09-20 14:51 UTC, 3vilhamster approved these changes

2023-09-21 08:12 UTC, 3vilhamster commented on internal/internal_task_handlers.go
> +			if canceledErr != nil && !errors.As(err, &canceledErr) {
canceledErr is always nil and err is checked for nil inside errors.As.

2023-09-21 08:12 UTC, 3vilhamster requested changes
Please revert recent change :)

2023-09-21 08:24 UTC, 3vilhamster commented on internal/internal_task_handlers.go
> +			if canceledErr != nil && !errors.As(err, &canceledErr) {
also, maybe put this into a method and add a test so you are 100% sure about the behaviour. 
Something like 
i.processHearbeatError(err)
and then add unit test with zaptest.Logger.

2023-09-21 11:18 UTC, 3vilhamster approved these changes
LGTM

2023-09-21 11:19 UTC, merged